### ISSUE TITLE
Unable to compile for aarch64 platform

### ISSUE THREAD

**Issue by gabekassel** [openthread/ot-qorvo#352]
I believe the static libraries do not support arm64. Please suggest the correct way to use this repo (or whether QGateway is required) to use this on an aarch64 platform. 

```
libQorvoQPG7015M_ftd.a: error adding symbols: file in wrong format
| collect2: error: ld returned 1 exit status
```

@thcu-gp

**Comment by thcu-gp** [comment]
Hi @gabekassel,

This repository currently does not support ARM64 

Check see https://github.com/Qorvo/qpg-openthread/tree/master/qpg7015m/doc for instructions to build for QPG7015M with static libraries from https://github.com/Qorvo/qpg-openthread
